version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mon-business-api-nestjs
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/mon_business?schema=public"
      NODE_ENV: production
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: mon-business-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mon_business
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: